<theme extends="webstandard" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="platform:/plugin/com.ibm.designer.domino.stylekits/schema/stylekit.xsd" >
	<resource dojoTheme="true">
		<content-type>text/css</content-type>
		<href>/.ibmxspres/dojoroot/dijit/themes/claro/claro.css</href>
	</resource>
	
	<control dojoTheme="true">
		<name>ViewRoot</name>
		<property>
			<name>styleClass</name>
			<value>claro</value>
		</property>
	</control>
</theme>
